# pyproject.toml
[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
console_output_style = "count"
addopts = "-qq --cov=custom_components.skybellgen --cov-report html"
testpaths = [
    "tests",
]