# pyproject.toml
[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
console_output_style = "count"
addopts = "-qq"
testpaths = [
    "tests",
]

[tool.coverage.report]
omit = [
    "custom_components/skybellgen/camera.py",
]
show_missing = true
fail_under = 100

[tool.coverage.run]
branch = false
source = [
    "custom_components/skybellgen",
]

[tool.coverage.html]
directory = "htmlcov"

[tool.pylint.MAIN]
init-hook = """
try: import pylint_venv
except ImportError: pass
else: pylint_venv.inithook()
"""

[tool.pylint.messages_control]
disable = [
    "abstract-method",
    "attribute-defined-outside-init",
    "broad-except",
    "chained-comparison",
    "duplicate-code",
    "import-error",
    "overridden-final-method",
    "too-few-public-methods",
    "unexpected-keyword-arg",
    "unused-argument",
    "consider-using-get",
]

[tool.mypy]
exclude_gitignore = true
ignore_missing_imports = true
exclude = [
    "tests",
]